// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB77WtpNm5FC4uyEOm7ENL0YHZu2ydIzto',
    appId: '1:582512223771:web:917f7e77d30d89ddebfabe',
    messagingSenderId: '582512223771',
    projectId: 'final-project-f8ca2',
    authDomain: 'final-project-f8ca2.firebaseapp.com',
    storageBucket: 'final-project-f8ca2.appspot.com',
    measurementId: 'G-2Q72CEYLLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbnBGI2r23G-i5EXTAtTpVfvLTzGjIhw0',
    appId: '1:582512223771:android:3f35337036dd3d5aebfabe',
    messagingSenderId: '582512223771',
    projectId: 'final-project-f8ca2',
    storageBucket: 'final-project-f8ca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALQC0fFkGg7hsygewL6z5bTffhRU2CDzA',
    appId: '1:582512223771:ios:6fd7fdc6f5543e7bebfabe',
    messagingSenderId: '582512223771',
    projectId: 'final-project-f8ca2',
    storageBucket: 'final-project-f8ca2.appspot.com',
    iosClientId: '582512223771-rmlfit65f4a2s6i9mhoa8fdhjhajhhfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.calorieTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALQC0fFkGg7hsygewL6z5bTffhRU2CDzA',
    appId: '1:582512223771:ios:6fd7fdc6f5543e7bebfabe',
    messagingSenderId: '582512223771',
    projectId: 'final-project-f8ca2',
    storageBucket: 'final-project-f8ca2.appspot.com',
    iosClientId: '582512223771-rmlfit65f4a2s6i9mhoa8fdhjhajhhfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.calorieTracker',
  );
}
